name: Update Google Scholar metrics

on:
  schedule:
    - cron:  '0 3 * * *'     # every day at 03:00 UTC
  workflow_dispatch:         # lets you run it manually too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install scholarly
        run: pip install scholarly

      - name: Run update script
        run: python scripts/update_scholar.py

      - name: Commit & push if changes
        run: |
          git diff --quiet || (
            git config --global user.name  "github-actions"
            git config --global user.email "action@github.com"
            git add public/data/scholar.json
            git commit -m "chore: nightly Scholar update"
            git push
          )
