name: Update Google Scholar metrics

on:
  schedule:
    - cron:  '0 3 * * *'     # every day at 03:00 UTC
  workflow_dispatch:         # lets you run it manually too
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Skip the job if *this* push was made by the bot itself
    if: github.actor != 'github-actions[bot]'

    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: |
          pip install "httpx<0.26"          # pinned for Scholarly
          pip install scholarly free-proxy

      - name: Run update script
        run: python scripts/update_scholar.py
        continue-on-error: true             # keep the workflow green if Scholar is down
        
      - name: Commit & push if metrics changed
        run: |
          git diff --quiet || (
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions@github.com"
            git add data/scholar.json
            git commit -m "chore: update Scholar metrics (auto)"
            git push
          )
